# Generated by Django 4.1 on 2026-02-13 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_project_created_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='evn_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evn_name', models.CharField(max_length=50)),
                ('environment_type', models.CharField(choices=[('dev', '开发'), ('test', '测试'), ('pre', '预生产')], max_length=10, verbose_name='环境类型')),
                ('test_object_config', models.TextField(verbose_name='测试对象配置')),
                ('database_config', models.TextField(verbose_name='数据库配置')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='front.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '环境配置',
                'verbose_name_plural': '环境配置',
                'db_table': 'evn_config',
                'unique_together': {('project', 'evn_name')},
            },
        ),
    ]
