# Generated by Django 4.1 on 2026-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0003_evn_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evn_config',
            name='environment_type',
        ),
        migrations.AddField(
            model_name='evn_config',
            name='description',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
