# Generated by Django 4.1 on 2026-02-14 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0004_remove_evn_config_environment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evn_config',
            name='database_config',
            field=models.TextField(blank=True, null=True, verbose_name='数据库配置'),
        ),
        migrations.AlterField(
            model_name='evn_config',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
