# Generated by Django 4.1 on 2026-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0006_alter_evn_config_database_config_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evn_config',
            name='database_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='数据库配置'),
        ),
        migrations.AlterField(
            model_name='evn_config',
            name='test_object_config',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='测试对象配置'),
        ),
    ]
